services:
  - postgresql
before_script:
- psql -c 'create user postgres_query_test;' -U postgres
- psql -c 'create database postgres_query_test;' -U postgres
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly

