[package]
name = "postgres_query"
version = "0.1.0"
authors = ["Christofer Nolander <christofer.nolander@gmail.com>"]
edition = "2018"

[lib]
name = "postgres_query"

[[example]]
name = "basic_select"

[dependencies]
postgres = "0.15.2"
postgres_query_derive = { path = "postgres_query_derive" }
