[package]
name = "postgres_query"
version = "0.1.1"
authors = ["Christofer Nolander <christofer.nolander@gmail.com>"]
description = "Define SQL queries with human-readable parameter names"
edition = "2018"
repository = "https://github.com/nolanderc/rust-postgres-query"
license = "MIT OR Apache-2.0"
readme = "../README.md"

[lib]
name = "postgres_query"

[[example]]
name = "basic_select"

[dependencies]
postgres = "0.15.2"
postgres_query_derive = { version = "0.1.1", path = "../postgres_query_derive" }
